#!/bin/bash

cd $(dirname $0)/..
BACKEND=$(cat config/BACKEND)
python -m rasa_nlu.train -c config/config_$BACKEND.json
if [[ -e models/default ]]
then
    cd models
    ln -s $(ls | tail -1) default
fi
