#!/bin/bash

cd $(dirname $0)/..
BACKEND=$(cat config/BACKEND)
python -m rasa_nlu.train -c config/config_$BACKEND.json
if [[ -e models/default || "$1" == "-f" ]]
then
    cd models
    rm -fv default
    ln -sv $(ls -tr | tail -1) default
fi
