#!/bin/bash

cd $(dirname $0)/..
BACKEND=$(cat config/BACKEND)
python -m rasa_nlu.train -c config/config_$BACKEND.json
if [[ -e models/default || "$1" == "-f" ]]
then
    cd models
    ln -sfv $(ls | tail -1) default
fi
